param(
    [string]$WorkspaceRoot = "C:\work\CoffeeGAME"
)

$ErrorActionPreference = "Stop"
Add-Type -AssemblyName System.Drawing

if (-not ("Hd2dAlphaBounds" -as [type])) {
    $alphaBoundsSource = @'
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.Runtime.InteropServices;

public static class Hd2dAlphaBounds
{
    public static Rectangle Find(Bitmap bitmap, Rectangle search, byte alphaThreshold)
    {
        Rectangle imageBounds = new Rectangle(0, 0, bitmap.Width, bitmap.Height);
        search.Intersect(imageBounds);
        if (search.Width <= 0 || search.Height <= 0)
            throw new ArgumentOutOfRangeException("search");

        // Locking a sub-rectangle can expose a stride whose backing buffer is
        // smaller than stride * rect.Height. Copying it as one block caused an
        // AccessViolation on Windows. Normalize once, lock the whole bitmap,
        // and copy one valid scanline at a time instead.
        using (Bitmap normalized = new Bitmap(bitmap.Width, bitmap.Height, PixelFormat.Format32bppArgb))
        {
            using (Graphics graphics = Graphics.FromImage(normalized))
            {
                graphics.CompositingMode = System.Drawing.Drawing2D.CompositingMode.SourceCopy;
                graphics.DrawImageUnscaled(bitmap, 0, 0);
            }

            BitmapData data = normalized.LockBits(imageBounds, ImageLockMode.ReadOnly, PixelFormat.Format32bppArgb);
            try
            {
                int rowBytes = Math.Abs(data.Stride);
                byte[] row = new byte[rowBytes];
                int searchWidth = search.Width;
                int searchHeight = search.Height;
                bool[] visible = new bool[searchWidth * searchHeight];
                for (int localY = 0; localY < searchHeight; localY++)
                {
                    int y = search.Top + localY;
                    IntPtr scanline = IntPtr.Add(data.Scan0, y * data.Stride);
                    Marshal.Copy(scanline, row, 0, rowBytes);
                    for (int localX = 0; localX < searchWidth; localX++)
                    {
                        int x = search.Left + localX;
                        visible[localY * searchWidth + localX] = row[x * 4 + 3] > alphaThreshold;
                    }
                }

                // Contact sheets generated by image models can let a sword tip
                // or hair lock bleed into the neighbouring nominal cell. Keep
                // the dominant connected subject and discard those islands.
                bool[] visited = new bool[visible.Length];
                int[] queue = new int[visible.Length];
                int bestArea = 0;
                int bestMinX = 0;
                int bestMinY = 0;
                int bestMaxX = -1;
                int bestMaxY = -1;
                for (int start = 0; start < visible.Length; start++)
                {
                    if (!visible[start] || visited[start])
                        continue;

                    int head = 0;
                    int tail = 0;
                    queue[tail++] = start;
                    visited[start] = true;
                    int area = 0;
                    int minLocalX = searchWidth;
                    int minLocalY = searchHeight;
                    int maxLocalX = -1;
                    int maxLocalY = -1;
                    while (head < tail)
                    {
                        int current = queue[head++];
                        int currentX = current % searchWidth;
                        int currentY = current / searchWidth;
                        area++;
                        if (currentX < minLocalX) minLocalX = currentX;
                        if (currentX > maxLocalX) maxLocalX = currentX;
                        if (currentY < minLocalY) minLocalY = currentY;
                        if (currentY > maxLocalY) maxLocalY = currentY;

                        for (int dy = -1; dy <= 1; dy++)
                        {
                            int nextY = currentY + dy;
                            if (nextY < 0 || nextY >= searchHeight) continue;
                            for (int dx = -1; dx <= 1; dx++)
                            {
                                if (dx == 0 && dy == 0) continue;
                                int nextX = currentX + dx;
                                if (nextX < 0 || nextX >= searchWidth) continue;
                                int next = nextY * searchWidth + nextX;
                                if (!visible[next] || visited[next]) continue;
                                visited[next] = true;
                                queue[tail++] = next;
                            }
                        }
                    }

                    if (area > bestArea)
                    {
                        bestArea = area;
                        bestMinX = minLocalX;
                        bestMinY = minLocalY;
                        bestMaxX = maxLocalX;
                        bestMaxY = maxLocalY;
                    }
                }

                if (bestArea == 0)
                    throw new InvalidOperationException("The selected cell contains no visible pixels.");

                const int padding = 3;
                int minX = Math.Max(search.Left, search.Left + bestMinX - padding);
                int minY = Math.Max(search.Top, search.Top + bestMinY - padding);
                int maxX = Math.Min(search.Right - 1, search.Left + bestMaxX + padding);
                int maxY = Math.Min(search.Bottom - 1, search.Top + bestMaxY + padding);
                return new Rectangle(minX, minY, maxX - minX + 1, maxY - minY + 1);
            }
            finally
            {
                normalized.UnlockBits(data);
            }
        }
    }

    public static void KeepLargestComponents(Bitmap bitmap, int componentCount, byte alphaThreshold)
    {
        if (componentCount < 1)
            throw new ArgumentOutOfRangeException("componentCount");

        Rectangle bounds = new Rectangle(0, 0, bitmap.Width, bitmap.Height);
        BitmapData data = bitmap.LockBits(bounds, ImageLockMode.ReadWrite, PixelFormat.Format32bppArgb);
        try
        {
            int width = bitmap.Width;
            int height = bitmap.Height;
            int strideBytes = Math.Abs(data.Stride);
            byte[] scanline = new byte[strideBytes];
            byte[] pixels = new byte[width * height * 4];
            for (int y = 0; y < height; y++)
            {
                Marshal.Copy(IntPtr.Add(data.Scan0, y * data.Stride), scanline, 0, strideBytes);
                Buffer.BlockCopy(scanline, 0, pixels, y * width * 4, width * 4);
            }

            int pixelCount = width * height;
            int[] componentIds = new int[pixelCount];
            for (int i = 0; i < componentIds.Length; i++) componentIds[i] = -1;
            int[] queue = new int[pixelCount];
            List<int> areas = new List<int>();

            for (int start = 0; start < pixelCount; start++)
            {
                if (pixels[start * 4 + 3] <= alphaThreshold || componentIds[start] >= 0)
                    continue;

                int componentId = areas.Count;
                int head = 0;
                int tail = 0;
                int area = 0;
                queue[tail++] = start;
                componentIds[start] = componentId;
                while (head < tail)
                {
                    int current = queue[head++];
                    int currentX = current % width;
                    int currentY = current / width;
                    area++;
                    for (int dy = -1; dy <= 1; dy++)
                    {
                        int nextY = currentY + dy;
                        if (nextY < 0 || nextY >= height) continue;
                        for (int dx = -1; dx <= 1; dx++)
                        {
                            if (dx == 0 && dy == 0) continue;
                            int nextX = currentX + dx;
                            if (nextX < 0 || nextX >= width) continue;
                            int next = nextY * width + nextX;
                            if (componentIds[next] >= 0 || pixels[next * 4 + 3] <= alphaThreshold) continue;
                            componentIds[next] = componentId;
                            queue[tail++] = next;
                        }
                    }
                }
                areas.Add(area);
            }

            bool[] keep = new bool[areas.Count];
            for (int selection = 0; selection < componentCount; selection++)
            {
                int bestId = -1;
                int bestArea = -1;
                for (int id = 0; id < areas.Count; id++)
                {
                    if (!keep[id] && areas[id] > bestArea)
                    {
                        bestId = id;
                        bestArea = areas[id];
                    }
                }
                if (bestId < 0) break;
                keep[bestId] = true;
            }

            for (int pixel = 0; pixel < pixelCount; pixel++)
            {
                int id = componentIds[pixel];
                if (id >= 0 && keep[id]) continue;
                int offset = pixel * 4;
                pixels[offset] = 0;
                pixels[offset + 1] = 0;
                pixels[offset + 2] = 0;
                pixels[offset + 3] = 0;
            }

            for (int y = 0; y < height; y++)
            {
                Array.Clear(scanline, 0, scanline.Length);
                Buffer.BlockCopy(pixels, y * width * 4, scanline, 0, width * 4);
                Marshal.Copy(scanline, 0, IntPtr.Add(data.Scan0, y * data.Stride), strideBytes);
            }
        }
        finally
        {
            bitmap.UnlockBits(data);
        }
    }

    public static void RemoveMagentaSpill(Bitmap bitmap)
    {
        Rectangle bounds = new Rectangle(0, 0, bitmap.Width, bitmap.Height);
        BitmapData data = bitmap.LockBits(bounds, ImageLockMode.ReadWrite, PixelFormat.Format32bppArgb);
        try
        {
            int strideBytes = Math.Abs(data.Stride);
            byte[] row = new byte[strideBytes];
            for (int y = 0; y < bitmap.Height; y++)
            {
                IntPtr scanline = IntPtr.Add(data.Scan0, y * data.Stride);
                Marshal.Copy(scanline, row, 0, strideBytes);
                for (int x = 0; x < bitmap.Width; x++)
                {
                    int offset = x * 4;
                    int blue = row[offset];
                    int green = row[offset + 1];
                    int red = row[offset + 2];
                    int alpha = row[offset + 3];
                    if (alpha == 0 || red <= 70 || blue <= 100 || red <= green + 35 || blue <= green + 35)
                        continue;

                    // The source uses a magenta key. Opaque key spill can remain
                    // after matte extraction, so shift only that hue toward the
                    // slime's authored deep-blue/cyan contour.
                    int cyanGreen = Math.Max(green, Math.Min(150, (int)Math.Round(blue * 0.30)));
                    row[offset + 1] = (byte)cyanGreen;
                    row[offset + 2] = (byte)Math.Min(red, Math.Max(8, (int)Math.Round(cyanGreen * 0.35)));
                }
                Marshal.Copy(row, 0, scanline, strideBytes);
            }
        }
        finally
        {
            bitmap.UnlockBits(data);
        }
    }
}
'@
    Add-Type -TypeDefinition $alphaBoundsSource -ReferencedAssemblies "System.Drawing"
}

function Export-Hd2dFrame {
    param(
        [Parameter(Mandatory)] [string]$SourcePath,
        [Parameter(Mandatory)] [System.Drawing.Rectangle]$SearchRect,
        [Parameter(Mandatory)] [string]$OutputPath,
        [int]$CanvasSize = 768,
        [int]$ContentWidth = 736,
        [int]$ContentHeight = 680,
        [int]$BottomMargin = 44,
        [int]$KeepComponents = 1,
        [switch]$RemoveMagentaSpill,
        [double]$ScaleOverride = 0
    )

    $source = [System.Drawing.Bitmap]::FromFile($SourcePath)
    try {
        $visible = [Hd2dAlphaBounds]::Find($source, $SearchRect, 3)
        $scale = if ($ScaleOverride -gt 0) {
            $ScaleOverride
        }
        else {
            [Math]::Min(
                $ContentWidth / [double]$visible.Width,
                $ContentHeight / [double]$visible.Height)
        }
        $width = [Math]::Max(1, [int][Math]::Round($visible.Width * $scale))
        $height = [Math]::Max(1, [int][Math]::Round($visible.Height * $scale))
        $x = [int][Math]::Round(($CanvasSize - $width) / 2.0)
        $y = $CanvasSize - $BottomMargin - $height
        if ($y -lt 4) { $y = 4 }

        $output = [System.Drawing.Bitmap]::new(
            $CanvasSize,
            $CanvasSize,
            [System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
        try {
            $graphics = [System.Drawing.Graphics]::FromImage($output)
            try {
                $graphics.Clear([System.Drawing.Color]::Transparent)
                $graphics.CompositingMode = [System.Drawing.Drawing2D.CompositingMode]::SourceCopy
                $graphics.CompositingQuality = [System.Drawing.Drawing2D.CompositingQuality]::HighQuality
                $graphics.InterpolationMode = [System.Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
                $graphics.PixelOffsetMode = [System.Drawing.Drawing2D.PixelOffsetMode]::HighQuality
                $graphics.SmoothingMode = [System.Drawing.Drawing2D.SmoothingMode]::HighQuality
                $destination = [System.Drawing.Rectangle]::new($x, $y, $width, $height)
                $graphics.DrawImage(
                    $source,
                    $destination,
                    $visible,
                    [System.Drawing.GraphicsUnit]::Pixel)
            }
            finally {
                $graphics.Dispose()
            }

            [Hd2dAlphaBounds]::KeepLargestComponents($output, $KeepComponents, 8)
            if ($RemoveMagentaSpill) {
                [Hd2dAlphaBounds]::RemoveMagentaSpill($output)
            }

            $directory = Split-Path -Parent $OutputPath
            New-Item -ItemType Directory -Path $directory -Force | Out-Null
            $output.Save($OutputPath, [System.Drawing.Imaging.ImageFormat]::Png)
        }
        finally {
            $output.Dispose()
        }
    }
    finally {
        $source.Dispose()
    }
}

function Export-Hd2dContactSheet {
    param(
        [Parameter(Mandatory)] [string]$InputDirectory,
        [Parameter(Mandatory)] [string]$OutputPath,
        [int]$Columns = 5,
        [int]$CellWidth = 240,
        [int]$CellHeight = 250
    )

    $files = @(Get-ChildItem -LiteralPath $InputDirectory -Filter "*.png" | Sort-Object Name)
    if ($files.Count -eq 0) { return }

    $rows = [int][Math]::Ceiling($files.Count / [double]$Columns)
    $sheet = [System.Drawing.Bitmap]::new(
        $Columns * $CellWidth,
        $rows * $CellHeight,
        [System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
    try {
        $graphics = [System.Drawing.Graphics]::FromImage($sheet)
        $font = [System.Drawing.Font]::new("Segoe UI", 11)
        $labelBrush = [System.Drawing.SolidBrush]::new([System.Drawing.Color]::White)
        $gridPen = [System.Drawing.Pen]::new([System.Drawing.Color]::FromArgb(80, 255, 255, 255))
        try {
            $graphics.Clear([System.Drawing.Color]::FromArgb(255, 45, 47, 52))
            $graphics.InterpolationMode = [System.Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
            for ($index = 0; $index -lt $files.Count; $index++) {
                $column = $index % $Columns
                $row = [int][Math]::Floor($index / $Columns)
                $cellX = $column * $CellWidth
                $cellY = $row * $CellHeight
                $graphics.DrawRectangle($gridPen, $cellX, $cellY, $CellWidth - 1, $CellHeight - 1)

                $image = [System.Drawing.Image]::FromFile($files[$index].FullName)
                try {
                    $availableWidth = $CellWidth - 12
                    $availableHeight = $CellHeight - 34
                    $scale = [Math]::Min(
                        $availableWidth / [double]$image.Width,
                        $availableHeight / [double]$image.Height)
                    $width = [int][Math]::Round($image.Width * $scale)
                    $height = [int][Math]::Round($image.Height * $scale)
                    $x = $cellX + [int][Math]::Round(($CellWidth - $width) / 2.0)
                    $y = $cellY + 4 + [int][Math]::Round(($availableHeight - $height) / 2.0)
                    $graphics.DrawImage($image, $x, $y, $width, $height)
                }
                finally {
                    $image.Dispose()
                }

                $label = [System.IO.Path]::GetFileNameWithoutExtension($files[$index].Name)
                $graphics.DrawString($label, $font, $labelBrush, $cellX + 6, $cellY + $CellHeight - 26)
            }
        }
        finally {
            $gridPen.Dispose()
            $labelBrush.Dispose()
            $font.Dispose()
            $graphics.Dispose()
        }

        $directory = Split-Path -Parent $OutputPath
        New-Item -ItemType Directory -Path $directory -Force | Out-Null
        $sheet.Save($OutputPath, [System.Drawing.Imaging.ImageFormat]::Png)
    }
    finally {
        $sheet.Dispose()
    }
}

$sheetRoot = Join-Path $WorkspaceRoot "art\hd2d\sheets"
$referenceRoot = Join-Path $WorkspaceRoot "art\hd2d\reference"
$heroOutput = Join-Path $WorkspaceRoot "art\hd2d\frames\hero"
$slimeOutput = Join-Path $WorkspaceRoot "art\hd2d\frames\slime"

$heroFrames = @(
    @{ Source = (Join-Path $referenceRoot "heroine-turnaround-v1.png"); Rect = [System.Drawing.Rectangle]::new(35, 0, 445, 946); Name = "hero_idle_down.png"; Scale = 0.77 },
    @{ Source = (Join-Path $referenceRoot "heroine-turnaround-v1.png"); Rect = [System.Drawing.Rectangle]::new(475, 0, 425, 946); Name = "hero_idle_right.png"; Scale = 0.77 },
    @{ Source = (Join-Path $referenceRoot "heroine-turnaround-v1.png"); Rect = [System.Drawing.Rectangle]::new(845, 0, 410, 946); Name = "hero_idle_up.png"; Scale = 0.77 },

    @{ Source = (Join-Path $sheetRoot "heroine-locomotion-v1.png"); Rect = [System.Drawing.Rectangle]::new(0, 0, 341, 768); Name = "hero_walk_down.png"; Scale = 1.0 },
    @{ Source = (Join-Path $sheetRoot "heroine-locomotion-v1.png"); Rect = [System.Drawing.Rectangle]::new(341, 0, 342, 768); Name = "hero_run_down.png"; Scale = 1.0 },
    @{ Source = (Join-Path $sheetRoot "heroine-locomotion-v1.png"); Rect = [System.Drawing.Rectangle]::new(683, 0, 341, 768); Name = "hero_walk_right.png"; Scale = 1.0 },
    @{ Source = (Join-Path $sheetRoot "heroine-locomotion-v1.png"); Rect = [System.Drawing.Rectangle]::new(0, 768, 430, 768); Name = "hero_run_right.png"; Scale = 1.0 },
    @{ Source = (Join-Path $sheetRoot "heroine-locomotion-v1.png"); Rect = [System.Drawing.Rectangle]::new(420, 768, 270, 768); Name = "hero_walk_up.png"; Scale = 1.0 },
    @{ Source = (Join-Path $sheetRoot "heroine-locomotion-v1.png"); Rect = [System.Drawing.Rectangle]::new(690, 768, 334, 768); Name = "hero_run_up.png"; Scale = 1.0 }
)

$actionNames = @(
    "hero_sword_down.png", "hero_sword_right.png", "hero_airslash_right.png",
    "hero_plunge_down.png", "hero_spin_down.png", "hero_magic_down.png"
)
$stateNames = @(
    "hero_jump_down.png", "hero_fall_down.png", "hero_land_down.png",
    "hero_spincharge_down.png", "hero_hurt_down.png", "hero_defeated_down.png"
)

foreach ($frame in $heroFrames) {
    Export-Hd2dFrame -SourcePath $frame.Source -SearchRect $frame.Rect `
        -OutputPath (Join-Path $heroOutput $frame.Name) -ScaleOverride $frame.Scale
}

for ($index = 0; $index -lt 6; $index++) {
    $column = $index % 3
    $row = [int][Math]::Floor($index / 3)
    $cell = [System.Drawing.Rectangle]::new($column * 418, $row * 627, 418, 627)
    Export-Hd2dFrame -SourcePath (Join-Path $sheetRoot "heroine-actions-v1.png") `
        -SearchRect $cell -OutputPath (Join-Path $heroOutput $actionNames[$index]) `
        -KeepComponents $(if ($actionNames[$index] -eq "hero_magic_down.png") { 2 } else { 1 }) `
        -ScaleOverride 1.285
    Export-Hd2dFrame -SourcePath (Join-Path $sheetRoot "heroine-states-v1.png") `
        -SearchRect $cell -OutputPath (Join-Path $heroOutput $stateNames[$index]) `
        -ScaleOverride 1.285
}

Export-Hd2dFrame -SourcePath (Join-Path $referenceRoot "hero-magic-release-v2.png") `
    -SearchRect ([System.Drawing.Rectangle]::new(0, 0, 1254, 1254)) `
    -OutputPath (Join-Path $heroOutput "hero_magic_release_v2.png") `
    -KeepComponents 16

$slimeNames = @(
    "slime_idle.png", "slime_squash.png", "slime_hop.png",
    "slime_windup.png", "slime_hurt.png", "slime_defeated.png"
)
for ($index = 0; $index -lt 6; $index++) {
    $column = $index % 3
    $row = [int][Math]::Floor($index / 3)
    $cell = [System.Drawing.Rectangle]::new($column * 512, $row * 512, 512, 512)
    Export-Hd2dFrame -SourcePath (Join-Path $sheetRoot "slime-actions-v1.png") `
        -SearchRect $cell -OutputPath (Join-Path $slimeOutput $slimeNames[$index]) `
        -CanvasSize 512 -ContentWidth 472 -ContentHeight 400 -BottomMargin 42 `
        -RemoveMagentaSpill
}

$unityHero = Join-Path $WorkspaceRoot "unity\CoffeeGame\Assets\CoffeeGame\Resources\Art\HD2D\Hero\Frames"
$unitySlime = Join-Path $WorkspaceRoot "unity\CoffeeGame\Assets\CoffeeGame\Resources\Art\HD2D\Slime\Frames"
New-Item -ItemType Directory -Path $unityHero -Force | Out-Null
New-Item -ItemType Directory -Path $unitySlime -Force | Out-Null
Copy-Item -Path (Join-Path $heroOutput "*.png") -Destination $unityHero -Force
Copy-Item -Path (Join-Path $slimeOutput "*.png") -Destination $unitySlime -Force

$previewRoot = Join-Path $WorkspaceRoot "art\hd2d\previews"
Export-Hd2dContactSheet -InputDirectory $heroOutput `
    -OutputPath (Join-Path $previewRoot "hero-frames-v1.png") -Columns 5
Export-Hd2dContactSheet -InputDirectory $slimeOutput `
    -OutputPath (Join-Path $previewRoot "slime-frames-v1.png") -Columns 3

Write-Host "Exported $($heroFrames.Count + $actionNames.Count + $stateNames.Count + 1) hero frames and $($slimeNames.Count) slime frames."
